export interface Category {
  id: string;
  name: string;
  color: string;
  description: string;
  pdfUrl: string;
}

export const categories: Category[] = [
  {
    id: "abrigos",
    name: "Abrigos",
    color: "from-primary to-primary/50",
    description: "Última colección de temporada",
    pdfUrl: "https://files.catbox.moe/dox51w.pdf",
  },
  {
    id: "basicos-y-comodos",
    name: "Basicos y Comodos",
    color: "from-primary to-primary/50",
    description: "",
    pdfUrl: "https://files.catbox.moe/2wvv8s.pdf",
  },
  {
    id: "botas",
    name: "Botas",
    color: "from-primary to-primary/50",
    description: "Más de 700 modelos disponibles",
    pdfUrl: "https://files.catbox.moe/b18xal.pdf",
  },
  {
    id: "caballeros",
    name: "Caballeros",
    color: "from-primary to-primary/50",
    description: "",
    pdfUrl: "https://files.catbox.moe/uheu94.pdf",
  },
  {
    id: "caballeros-2",
    name: "Caballeros",
    color: "from-primary to-primary/50",
    description: "La combinación perfecta entre estilo y confort",
    pdfUrl: "https://files.catbox.moe/o637hg.pdf",
  },
  {
    id: "coleccion-ella",
    name: "Colección Ella",
    color: "from-primary to-primary/50",
    description: "El estilo que marca la temporada",
    pdfUrl: "https://files.catbox.moe/vmuojq.pdf",
  },
  {
    id: "dulces-suenos",
    name: "Dulces Sueños",
    color: "from-primary to-primary/50",
    description: "Tu zona de confort empieza aquí",
    pdfUrl: "https://files.catbox.moe/noupzk.pdf",
  },
  {
    id: "escolar-urbano",
    name: "Escolar Urbano",
    color: "from-primary to-primary/50",
    description: "",
    pdfUrl: "https://files.catbox.moe/j2ez8v.pdf",
  },
  {
    id: "escolar",
    name: "Escolar",
    color: "from-primary to-primary/50",
    description: "El mejor regreso a clases",
    pdfUrl: "https://files.catbox.moe/da2q05.pdf",
  },
  {
    id: "exclusivos",
    name: "Exclusivos",
    color: "from-primary to-primary/50",
    description: "Tu estilo, nuestra firma",
    pdfUrl: "https://files.catbox.moe/n6oyhk.pdf",
  },
  {
    id: "importados",
    name: "Importados",
    color: "from-primary to-primary/50",
    description: "Calidad y estilo internacional",
    pdfUrl: "https://files.catbox.moe/zdfgku.pdf",
  },
  {
    id: "jeans",
    name: "jeans",
    color: "from-primary to-primary/50",
    description: "Diseñados para moverse contigo",
    pdfUrl: "https://files.catbox.moe/ke1puc.pdf",
  },
  {
    id: "kids",
    name: "Kids",
    color: "from-primary to-primary/50",
    description: "Todo en uno para los más pequeños",
    pdfUrl: "https://files.catbox.moe/ekcsae.pdf",
  },
  {
    id: "suenos-en-peluche",
    name: "Sueños en peluche",
    color: "from-primary to-primary/50",
    description: "Tu personaje favorito, listo para abrazarte",
    pdfUrl: "https://files.catbox.moe/ycr445.pdf",
  },
  {
    id: "pijamas",
    name: "Pijamas",
    color: "from-primary to-primary/50",
    description: "",
    pdfUrl: "https://files.catbox.moe/5cmjft.pdf",
  },
  {
    id: "ropa-de-vestir",
    name: "Ropa de vestir",
    color: "from-primary to-primary/50",
    description: "Haz que el espejo se enamore más de ti",
    pdfUrl: "https://files.catbox.moe/5qznks.pdf",
  },
  {
    id: "ropa-interior",
    name: "Ropa interior",
    color: "from-primary to-primary/50",
    description: "",
    pdfUrl: "https://files.catbox.moe/yr8zts.pdf",
  },
  {
    id: "sandalias",
    name: "Sandalias",
    color: "from-primary to-primary/50",
    description: "",
    pdfUrl: "https://files.catbox.moe/bzobwh.pdf",
  },
  {
    id: "sport",
    name: "Sport",
    color: "from-primary to-primary/50",
    description: "",
    pdfUrl: "https://files.catbox.moe/y81zto.pdf",
  },
  {
    id: "todo-en-uno",
    name: "Todo en uno",
    color: "from-primary to-primary/50",
    description: "",
    pdfUrl: "https://files.catbox.moe/wdywjr.pdf",
  },
  {
    id: "uniformes",
    name: "Uniformes",
    color: "from-primary to-primary/50",
    description: "Uniformes medicos y chef",
    pdfUrl: "https://files.catbox.moe/r9nbhs.pdf",
  },
  {
    id: "urbano-trendy",
    name: "Urbano, Lo más trendy",
    color: "from-primary to-primary/50",
    description: "",
    pdfUrl: "https://files.catbox.moe/75yln5.pdf",
  },
  {
    id: "urbano-otono-invierno",
    name: "Urbano, Otoño Invierno",
    color: "from-primary to-primary/50",
    description: "",
    pdfUrl: "https://files.catbox.moe/1xlqkn.pdf",
  },
  {
    id: "zapato-de-vestir",
    name: "Zapato de Vestir",
    color: "from-primary to-primary/50",
    description: "",
    pdfUrl: "https://files.catbox.moe/1xlqkn.pdf",
  },
];
